import { createApp } from 'vue';
import ElementPlus from 'element-plus';
import zhCn from 'element-plus/es/locale/lang/zh-cn';
import 'element-plus/dist/index.css';
import '@fontsource/ubuntu/400.css';
import '@fontsource/ubuntu/700.css';
import '@fontsource/noto-sans-sc/chinese-simplified-400.css';
import '@fontsource/noto-sans-sc/chinese-simplified-700.css';
import 'highlight.js/styles/github.css';
import './style.css';
import App from './App.vue';
import { router } from './router';
createApp(App).use(router).use(ElementPlus, { locale: zhCn }).mount('#app');
